### PR TITLE
Add docker files and docs

### PR DESCRIPTION
**Pull request by yunimoo**
https://github.com/moebooru/moebooru/issues/233

This commit adds in docker compose and Dockerfile for deploying moebooru. Three separate psql databases are created for each environment. Sample configurations are also provided.

Let me know if I can clarify or fix anything.

### CODE REVIEW

**Comment by nanaya** [comment]
please follow the latest/upcoming rails' docker setup more closely. mainly separate images for prod (with prebuilt assets etc) and dev/test (bind mount/devcontainer). also I'm pretty sure arm64 image contains all the required dependencies

**Comment by yunimoo** [comment]
> please follow the latest/upcoming rails' docker setup more closely. mainly separate images for prod (with prebuilt assets etc) and dev/test (bind mount/devcontainer). also I'm pretty sure arm64 image contains all the required dependencies

I've modified the Dockerfile to create targets for the three separate images. I also modularized the `docker-compose.yml` to use environment specific files in `.docker` like `docker-compose.dev.yml` and `moebooru-app.dev.env.example`. These are mostly responsible for setting the volumes environment-specific. Unless you would like this reverted, the `docker-compose.yml` only deploys the database responsible for the environment to run in.

For the production image, I made sure to run `bundle exec rake assets:precompile`. Would that be enough?

I'm not able to test out the arm64 image, but the alpine base image doesn't include other tools like those related to accessing the postgres database.

Not sure if I fully addressed your concerns but feel free to correct me.

**Comment by nanaya** [comment]
sorry, I'm not quite sure where to begin with with this pr

**Comment by yunimoo** [comment]
> sorry, I'm not quite sure where to begin with with this pr

This is understandable since the PR is quite large... If you would like I can split it up into smaller ones. The PR builds the image through the [Dockerfile](https://github.com/moebooru/moebooru/pull/237/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1) and the targets are [specified based on the rails environment that is set.](https://github.com/moebooru/moebooru/pull/237/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R30). Which means that the user can specify an environment to build by setting the `RAILS_ENV` environment variable.

The production environment precompiles the assets, while the development and test environments mount the current project.

The Dockerfile and docker-compose.yml in the root of the project should be enough for deploying through Docker compose via `docker compose up`. However, this would be incomplete since environment variables need to be set. I'm not sure if it's easy/convenient to do so manually for (as environment variables) all of the ones listed in the [README](https://github.com/moebooru/moebooru/pull/237/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R66-R77).

Instead, I added three separate environment files that docker compose can read. That's the `.docker/moebooru-app.<RAILS_ENV>.env.example` and also `.docker/moebooru-db.env.example`. Instead of having a script that assigns these environment variables, these files can be called while building, and deploying the container instead. So each of the environment files have separate configurations that can be set separately (i.e. [`HOST_PORT`](https://github.com/moebooru/moebooru/pull/237/files#diff-7fa409bbaf730bbe3cd5aa306e6fddb989d3b83385b57dc927167b6952243108R22) could be 9000 instead). 

Also, to completely isolate the environments, docker compose has the ability to override / add in more to the deployment. That can be seen in the `.docker` directory. For the development's override: [`.docker/docker-compose.dev.yml`](https://github.com/moebooru/moebooru/pull/237/files#diff-70c497aca504f5dea223d5cb389075b6cceb331f79f14da62c9a5a6bf5797a5dR1) This adds in the mounts for the DB and app that are specified in the environment files: [.docker/moebooru-app.dev.env.example](https://github.com/moebooru/moebooru/pull/237/files#diff-d165c12de44d34c1ae6ad8b57c4393ded9a516d130f89db5c8ac4a79c9074f2aR25) and [.docker/moebooru-db.env.example](https://github.com/moebooru/moebooru/pull/237/files#diff-f211dcba7e038e2f1240cb97c92bc7745ab8d400143123711ff4f3b0f52720cbR3). These can be modified to suit the deployment as required, since the DB could exist elsewhere.

----

For testing this PR, I used the commands in the README, but there are some things you will need to add in. More specifically, you only need to [specify the DB paths for the volumes](https://github.com/moebooru/moebooru/pull/237/files#diff-f211dcba7e038e2f1240cb97c92bc7745ab8d400143123711ff4f3b0f52720cbR1) so that data persists even after destroying the container.

If it's the first time the DB is deployed, it will also need to be inited and migrated which is shown at the top of each environment file for the app deployment. (i.e. [`.docker/docker-compose.dev.yml`](https://github.com/moebooru/moebooru/pull/237/files#diff-d165c12de44d34c1ae6ad8b57c4393ded9a516d130f89db5c8ac4a79c9074f2aR1-R10)) Subsequently, the user can swap this out with the `migrate` for future deployments. These are ran at the start of the container's deployment.

Once you set the DB volume paths and the init and migrated in the command params, you can deploy each environment separately, as [outlined here](https://github.com/moebooru/moebooru/pull/237/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R85-R95). (This deploys the `development` environment but you can change it easily to the other environment files)

----

If you have any questions, or concerns about this PR I can try my best to clarify them. In short:
* Deploys 1 App
* Deploys 1 Postgres DB
* Users can specify environments to deploy + any configs as needed

**Comment by nanaya** [comment]
I mean, I feel writing one on my own would be faster than trying to get this pr in a more ideal state

**Comment by yunimoo** [comment]
> I mean, I feel writing one on my own would be faster than trying to get this pr in a more ideal state

Understood! Thanks for the feedback, I'll close this PR then

**Comment by luoli233** [comment]
Hello, can your Docker write a one click script for configuration

**Pull request closed without merging**
